[font]
size = 11.0

[font.normal]
family = "Comic Mono"
#family = "JetBrains Mono"
#family = "mononoki"
#family = "Iosevka"
style = "Regular"

[window]
opacity = 0.98

[window.padding]
x = 18
y = 16

[selection]
save_to_clipboard = true
